version: "3"

services:
  rails: 
    build: .
    ports:
      - "3000:3000"
    command:
      bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
      # - node-data:/app/node_modules

  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:      
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app_development
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    command:
      - --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
  # node-data: